version: "3.9"

services:

  # FAST API
  api:
    build:
      context: .
      dockerfile: .docker/local/api/Dockerfile
    image: api-module-image:latest
    env_file: .env
    command: /start
    volumes:
      - .:/app
    networks:
      - local
    ports:
      - "8010:8000"
    depends_on:
      - redis
      - celery

  # CELERY BACKEND
  redis:
    image: redis:7-alpine
    container_name: redis-backend
    networks:
      - local
    ports:
      - "6379:6379"

#  # CELERY BROKER
#  rabbitmq:
#    build: api/rabbitmq_service/
#    container_name: rabbitmq-broker
#    env_file: .env
#    networks:
#      - production-boilerplate
#    ports:
#      - "5672:5672"
#      - "15672:15672"

  # CELERY WORKER
  celery:
    image: api-module-image:latest
    container_name: celery-worker
    env_file: .env
    networks:
      - local
    command: /start-celeryworker
    volumes:
      - .:/app
    depends_on:
      - redis

  # CELERY MONITOR
  flower:
    image: api-module-image:latest
    container_name: celery-flower
    env_file: .env
    command: /start-flower
    volumes:
      - .:/app
    networks:
      - local
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery

networks:
  local:
    driver: bridge
